### ISSUE TITLE
Fix to automatically build pickle files

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/NINJA-Shogun#1]
On a new project pull, the software should lazy load pickle files needed for computation. If they can't be found at the location, then make them when they are needed.

An example bug log:
python /project/flatiron/dan/shogun/src/bin/kegg_parse_img_ids.py -i . -o kegg.csv
Traceback (most recent call last):
  File "/project/flatiron/dan/shogun/src/bin/kegg_parse_img_ids.py", line 77, in <module>
    main()
  File "/project/flatiron/dan/shogun/src/bin/kegg_parse_img_ids.py", line 61, in main
    img_map = IMGMap.load()
  File "/project/flatiron/dan/shogun/src/lib/shogun/shogun/utilities/pickle_class.py", line 25, in load
    raise error
  File "/project/flatiron/dan/shogun/src/lib/shogun/shogun/utilities/pickle_class.py", line 21, in load
    with open(self_dump, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/project/flatiron/dan/shogun/data/pickle/IMGMap.pkl'

**Comment by bhillmann** [comment]
resolve #07e590a7c98c9f6f2f0658495a8c8287361d42a0

**Comment by bhillmann** [comment]
07e590a7c98c9f6f2f0658495a8c8287361d42a0
